name: CI
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
        branches: [main]
jobs:
    ci:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['18.x', '20.x']
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install pnpm 8.6.12
              uses: pnpm/action-setup@v4
              with:
                  version: 8.6.12

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Lint
              run: pnpm run lint

            - name: Test
              run: pnpm run test -- --ci --coverage --maxWorkers=2

            - name: Build
              run: pnpm run build
